### ISSUE TITLE
error validator ?

### ISSUE THREAD

**Issue by thierry-laval** [wass08/animated-text#1]
`<p class = "animated-text animated-text - typing" speed = "50" delay = "2200"> blablabla </p>
`Makes me an error in the validator.
Attribute “speed” not allowed on element “p” at this point.
Attribute “delay” not allowed on element “p” at this point.
An idea ?

**Comment by wass08** [comment]
Hi,
Seems the validator doesn't like the attributes speed and delay. If you really want to skip those messages you can replace the "p" tag with a "div"

**Comment by thierry-laval** [comment]
Hi :-)

I try again with a div but it does the same error ...

**Comment by thierry-laval** [comment]
` data-speed="" data-delay="" `
actually it works well by adding data (also on .js of course). 
Thank you for your very nice little tips 
😎

**Comment by wass08** [comment]
Excellent,I will use data- before custom attributes in next videos to avoid this !
You're welcome 🙏
